#!/bin/sh

bg=$(grep feh .fehbg | cut --delimiter=\' --fields=2)

echo $bg

choices="random
move
open
rename
trash"

choice=$(echo "$choices" | dmenu -i -p "background $bg")

case "$choice" in 
	random) feh --recursive --randomize --bg-fill ~/Pictures;;
	open) xdg-open $bg;;
	
	trash) gio trash $bg; feh --recursive --randomize --bg-fill ~/Pictures;;

esac
	



